/* global module */
/**
 * Semantic theme tokens for Daftar design system.
 * Serves as the single source of truth for Tailwind configuration and JavaScript/React Native styling.
 */
const tokens = {
  colors: {
    'surface': 'var(--color-surface)',
    'surface-dim': 'var(--color-surface-dim)',
    'surface-bright': 'var(--color-surface-bright)',
    'surface-container-lowest': 'var(--color-surface-container-lowest)',
    'surface-container-low': 'var(--color-surface-container-low)',
    'surface-container': 'var(--color-surface-container)',
    'surface-container-high': 'var(--color-surface-container-high)',
    'surface-container-highest': 'var(--color-surface-container-highest)',
    'on-surface': 'var(--color-on-surface)',
    'on-surface-variant': 'var(--color-on-surface-variant)',
    'inverse-surface': 'var(--color-inverse-surface)',
    'inverse-on-surface': 'var(--color-inverse-on-surface)',
    'outline': 'var(--color-outline)',
    'outline-variant': 'var(--color-outline-variant)',
    'surface-tint': 'var(--color-surface-tint)',
    'primary': 'var(--color-primary)',
    'on-primary': 'var(--color-on-primary)',
    'primary-container': 'var(--color-primary-container)',
    'on-primary-container': 'var(--color-on-primary-container)',
    'inverse-primary': 'var(--color-inverse-primary)',
    'secondary': 'var(--color-secondary)',
    'on-secondary': 'var(--color-on-secondary)',
    'secondary-container': 'var(--color-secondary-container)',
    'on-secondary-container': 'var(--color-on-secondary-container)',
    'tertiary': 'var(--color-tertiary)',
    'on-tertiary': 'var(--color-on-tertiary)',
    'tertiary-container': 'var(--color-tertiary-container)',
    'on-tertiary-container': 'var(--color-on-tertiary-container)',
    'error': 'var(--color-error)',
    'on-error': 'var(--color-on-error)',
    'error-container': 'var(--color-error-container)',
    'on-error-container': 'var(--color-on-error-container)',
    'primary-fixed': 'var(--color-primary-fixed)',
    'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
    'on-primary-fixed': 'var(--color-on-primary-fixed)',
    'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
    'secondary-fixed': 'var(--color-secondary-fixed)',
    'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
    'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
    'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
    'tertiary-fixed': 'var(--color-tertiary-fixed)',
    'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
    'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
    'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
    'background': 'var(--color-background)',
    'on-background': 'var(--color-on-background)',
    'surface-variant': 'var(--color-surface-variant)'
},

  typography: {
    'amount-display': {
      fontFamily: 'JetBrainsMono',
      fontSize: '40px',
      fontWeight: '700',
      lineHeight: '48px',
      letterSpacing: '-0.02em',
    },
    'amount-display-mobile': {
      fontFamily: 'JetBrainsMono',
      fontSize: '32px',
      fontWeight: '700',
      lineHeight: '40px',
      letterSpacing: '-0.02em',
    },
    'headline-lg': {
      fontFamily: 'Inter',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '32px',
    },
    'headline-md': {
      fontFamily: 'Inter',
      fontSize: '20px',
      fontWeight: '600',
      lineHeight: '28px',
    },
    'body-lg': {
      fontFamily: 'Inter',
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '24px',
    },
    'body-sm': {
      fontFamily: 'Inter',
      fontSize: '14px',
      fontWeight: '400',
      lineHeight: '20px',
    },
    'label-mono': {
      fontFamily: 'JetBrainsMono',
      fontSize: '12px',
      fontWeight: '500',
      lineHeight: '16px',
      letterSpacing: '0.05em',
    },
    'label-caps': {
      fontFamily: 'Inter',
      fontSize: '11px',
      fontWeight: '700',
      lineHeight: '16px',
      letterSpacing: '0.1em',
    },
  },
  rounded: {
    'sm': '0.125rem',
    'DEFAULT': '0.25rem',
    'md': '0.375rem',
    'lg': '0.5rem',
    'xl': '0.75rem',
    'full': '9999px',
  },
  spacing: {
    'unit': '4px',
    'gutter': '16px',
    'margin-mobile': '16px',
    'margin-desktop': '32px',
    'touch-target': '44px',
  },
};

module.exports = { tokens };
